// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi7QPDNynONlFspV5-tw9vwRaQyHAKVzw',
    appId: '1:901017901767:web:8bb92da1244a928b1ffce2',
    messagingSenderId: '901017901767',
    projectId: 'leituras-mc',
    authDomain: 'leituras-mc.firebaseapp.com',
    storageBucket: 'leituras-mc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK55KRpkscCaHBJSWDbT2dJFKX9_qV660',
    appId: '1:901017901767:android:42718ab6ab5bb1f41ffce2',
    messagingSenderId: '901017901767',
    projectId: 'leituras-mc',
    storageBucket: 'leituras-mc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgpwBFJYSnz1Nssx_zlYMY6xwGLzJplaU',
    appId: '1:901017901767:ios:a80c52ca84c93a821ffce2',
    messagingSenderId: '901017901767',
    projectId: 'leituras-mc',
    storageBucket: 'leituras-mc.firebasestorage.app',
    iosBundleId: 'com.example.leiturasMc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgpwBFJYSnz1Nssx_zlYMY6xwGLzJplaU',
    appId: '1:901017901767:ios:a80c52ca84c93a821ffce2',
    messagingSenderId: '901017901767',
    projectId: 'leituras-mc',
    storageBucket: 'leituras-mc.firebasestorage.app',
    iosBundleId: 'com.example.leiturasMc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCi7QPDNynONlFspV5-tw9vwRaQyHAKVzw',
    appId: '1:901017901767:web:5f1dc89dabb3a06d1ffce2',
    messagingSenderId: '901017901767',
    projectId: 'leituras-mc',
    authDomain: 'leituras-mc.firebaseapp.com',
    storageBucket: 'leituras-mc.firebasestorage.app',
  );

}